<template>
<div class="clear">
  <Header v-bind:moduleId="moduleId" v-bind:menu="headerMenu"></Header>
  <Menu v-bind:menu="leftBarMenu"></Menu>
  <div class="main-panel">
    <div class="test-detail">
      <div style="margin:10px 0px 40px 0px;">
        edit-test-id:<span style="margin:0px 10px">{{testData.id}}</span>
        origin-test-id:<span style="margin:0px 10px">{{testData.fromId}}</span>
      </div>
      <Modal v-model="inboundReqModal.show" width="1000">
        <p slot="header" style="color:#666;text-align:center">
          <span style="position: relative;top: 1px;">eidt the inbound request</span>
        </p>
        <div style="height:400px;word-break:break-all;overflow-y:scroll;padding-bottom:10px;">
          <Tabs v-model="inboundReqModal.selectedTab" style="height: 390px;" @on-click="inboundReqTabClicked">
            <TabPane label="ddl" name="ddl">
              <div class="ddl-codec-select" style="margin-bottom:20px;border-radius:4px;padding: 10px;border: 1px solid #eee;">
                <span style="float:left;line-height:32px;">ddl decoder:</span>
                <Select v-model="inboundReqModal.pluginSettings.pluginName" style="width:200px;margin-left:10px;float:left;" @on-change="onInboundReqDDLPluginChanged">
                  <Option v-for="pluginName in inboundReqModal.pluginNameList" :value="pluginName" :key="pluginName">{{ pluginName }}</Option>
                </Select>
                <div v-for="setting in inboundReqModal.pluginSettings.settings">
                  <div style="float:left;line-height:32px;margin-left:10px;" >{{ setting.name }}:</div>
                  <Select v-if="setting.type=='select'" v-model="setting.currentValue" style="min-width:120px;width:auto;margin-left:10px;float:left;">
                    <Option v-for="value in setting.values" :value="value" :key="value">{{ value }}</Option>
                  </Select>
                </div>
                <Button type="primary" v-on:click="reInboundReqToDDL" style="float:left;margin-left:20px;">preview</Button>
                <div style="clear:both;" ></div>
              </div>
              <Input v-model="inboundReqModal.ddl" type="textarea" :autosize="{minRows: 14}" placeholder="modify the request through DDL." style="width: 100%;"></Input>
            </TabPane>
            <TabPane label="preview (bytes generated by ddl)" name="content">
              <div style="height:400px;word-break:break-all;overflow-y:scroll;padding-bottom:10px;" v-html="inboundReqModal.content">
              </div>
            </TabPane>
            <TabPane label="origin bytes" name="origin_content">
              <div style="height:400px;word-break:break-all;overflow-y:scroll;padding-bottom:10px;" v-html="inboundReqModal.originContent">
              </div>
            </TabPane>
          </Tabs>
        </div>
        <div slot="footer">
          <div @click="inboundReqModal.show = false" style="cursor:pointer;float:right;width:28px;">close</div>
          <div @click="inboundReqSaveClicked()" style="cursor:pointer;float:right;width:28px;margin-right:20px" v-bind:class="{ hide: !inboundReqModal.showSave }">save</div>
          <div @click="inboundReqRestoreClicked()" style="cursor:pointer;float:left;width:90px;text-align:left" v-bind:class="{ hide: !inboundReqModal.showRestore }">restore to origin</div>
          <div style="clear:both;"></div>
        </div>
      </Modal>
      <Modal v-model="inboundRespModal.show" width="1000">
        <p slot="header" style="color:#666;text-align:center">
          <span style="position: relative;top: 1px;">no need to edit inbound response</span>
        </p>
        <div style="height:400px;word-break:break-all;overflow-y:scroll;padding-bottom:10px;">
          <div style="height:390px;word-break:break-all;overflow-y:scroll;padding-bottom:10px;" v-html="inboundRespModal.content">
          </div>
        </div>
        <div slot="footer">
          <div @click="inboundRespModal.show = false" style="cursor:pointer;float:right;width:28px;">close</div>
          <div style="clear:both;"></div>
        </div>
      </Modal>
      <Modal v-model="outboundReqModal.show" width="1000">
        <p slot="header" style="color:#666;text-align:center">
          <span style="position: relative;top: 1px;">how the request been matched</span>
        </p>
        <div style="height:400px;word-break:break-all;overflow-y:scroll;padding-bottom:10px;">
          <div class="match-type">
            <span style="margin-right:20px;">matched by:</span>
            <RadioGroup v-model="outboundReqModal.matchType">
              <Radio label="0">
                <span>Similarity</span>
              </Radio>
              <Radio label="1">
                <span>Containment</span>
              </Radio>
            </RadioGroup>
          </div>
          <Input v-model="outboundReqModal.content" type="textarea" :autosize="{minRows: 18}" placeholder="specify the content to match." style="width: 100%;margin-top:20px;"></Input>
        </div>
        <div slot="footer">
          <div @click="outboundReqModal.show = false" style="cursor:pointer;float:right;width:28px;">close</div>
          <div @click="outboundReqSaveClicked()" style="cursor:pointer;float:right;width:28px;margin-right:20px">save</div>
          <div @click="outboundReqRestoreClicked()" style="cursor:pointer;float:left;width:90px;text-align:left" v-bind:class="{ hide: outboundReqModal.fromIndex<0 }">restore to origin</div>
          <div style="clear:both;"></div>
        </div>
      </Modal>
      <Modal v-model="outboundRespModal.show" width="1000">
        <p slot="header" style="color:#666;text-align:center">
          <span style="position: relative;top: 1px;">eidt the outbound response</span>
        </p>
        <div style="height:400px;word-break:break-all;overflow-y:scroll;padding-bottom:10px;">
          <Tabs v-model='outboundRespModal.selectedTab' style="height: 390px;" @on-click="outboundRespTabClicked">
            <TabPane label="ddl" name="ddl">
              <div class="ddl-codec-select" style="margin-bottom:20px;border-radius:4px;padding: 10px;border: 1px solid #eee;">
                <span style="float:left;line-height:32px;">ddl decoder:</span>
                <Select v-model="outboundRespModal.pluginSettings.pluginName" style="width:200px;margin-left:10px;float:left;" @on-change="onOutboundRespDDLPluginChanged">
                  <Option v-for="pluginName in outboundRespModal.pluginNameList" :value="pluginName" :key="pluginName">{{ pluginName }}</Option>
                </Select>
                <div v-for="setting in outboundRespModal.pluginSettings.settings">
                  <div style="float:left;line-height:32px;margin-left:10px;" >{{ setting.name }}:</div>
                  <Select v-if="setting.type=='select'" v-model="setting.currentValue" style="min-width:120px;width:auto;margin-left:10px;float:left;">
                    <Option v-for="value in setting.values" :value="value" :key="value">{{ value }}</Option>
                  </Select>
                </div>
                <Button type="primary" v-on:click="reParseOutboundRespToDDL" style="float:left;margin-left:20px;">preview</Button>
                <div style="clear:both;" ></div>
              </div>
              <Input v-model="outboundRespModal.ddl" type="textarea" :rows="14" placeholder="modify the request through DDL." style="width: 100%;"></Input>
            </TabPane>
            <TabPane label="preview (bytes generated by ddl) " name="content">
              <div style="height:400px;word-break:break-all;overflow-y:scroll;padding-bottom:10px;" v-html="outboundRespModal.content">
              </div>
            </TabPane>
            <TabPane label="origin bytes" name="origin_content">
              <div style="height:400px;word-break:break-all;overflow-y:scroll;padding-bottom:10px;" v-html="outboundRespModal.originContent">
              </div>
            </TabPane>
          </Tabs>
        </div>
        <div slot="footer">
          <div @click="outboundRespModal.show = false" style="cursor:pointer;float:right;width:28px;">close</div>
          <div @click="outboundRespSaveClicked()" style="cursor:pointer;float:right;width:28px;margin-right:20px" v-bind:class="{ hide: !outboundRespModal.showSave }">save</div>
          <div @click="outboundRespRestoreClicked()" style="cursor:pointer;float:left;width:90px;text-align:left" v-bind:class="{ hide: !outboundRespModal.showRestore }">restore to origin</div>
          <div style="clear:both;"></div>
        </div>
      </Modal>
      <div class="test-data" v-bind:class="{ hide: testData.inbound.request=='' }">
        <div style="float:left">
          <div class="inbound-request bytes">
            <div class="data-item" v-on:click="inboundReqClicked">{{limitLength(base64decode(testData.inbound.request))}}</div>
            <Icon type="arrow-right-a"></Icon>
            <div style="clear:both;"></div>
          </div>
          <div class="inbound-response bytes" v-bind:style="{top: inboundRespTop+'px'}" style="position: relative;">
            <div class="data-item" v-on:click="inboundRespClicked">{{limitLength(base64decode(testData.inbound.response))}}</div>
            <Icon type="arrow-left-a"></Icon>
            <div style="clear:both;"></div>
          </div>
        </div>
        <div v-bind:style="{height: splitLineHeight+'px'}" style="float:left;width:1px;background: #CCC; margin:0px 2px;"></div>
        <div style="float:left">
          <div v-for="(outbound,index) in testData.outbounds" class="edit-outbound">
            <div class="outbound" v-bind:class="{first:index==0}">
              <Icon type="minus-round" color="white" v-on:click="onDeleteClicked(index)"></Icon>
              <div class="outbound-request bytes">
                <Icon type="arrow-right-a"></Icon>
                <div class="data-item" v-on:click="outboundReqClicked(index)">{{limitLength(base64decode(outbound.request))}}</div>
                <div style="clear:both;"></div>
              </div>
              <div class="outbound-response bytes">
                <Icon type="arrow-left-a"></Icon>
                <div class="data-item" v-on:click="outboundResponseClicked(index)">{{limitLength(base64decode(outbound.response))}}</div>
                <div style="clear:both;"></div>
              </div>
            </div>
            <Icon type="plus-round" color="white" v-on:click="onAddClicked(index+1)"></Icon>
            <div style="clear:both;"></div>
          </div>
          <div class="icon-fix" v-bind:class="{hide:testData.outbounds.length>0}">
            <Icon type="plus-round" color="white" v-on:click="onAddClicked(0)"></Icon>
          </div>
        </div>
      </div>
    </div>
  </div>
  <Footer></Footer>
</div>
</template>

<script>
let Base64 = require('js-base64').Base64;
import Header from '../components/Header.vue'
import Footer from '../components/Footer.vue'
import Menu from '../components/Menu.vue'
export default {
  name: 'Edit',
  components: { Header,Footer,Menu },
  data () {
    return {
      moduleId:0,
      testId:this.$route.params.id,
      headerMenu:[],
      leftBarMenu:[],
      testData:{
        inbound:{
          request:''
        },
        outbounds:[]
      },
      originTest:{
        
      },
      inboundRespTop:0,
      splitLineHeight:200,
      heightPerOutboundCall:160,
      modalContent:'',
      inboundReqModal:{
        show:false,
        selectedTab:'ddl',
        ddl:'',
        content:'',
        originContent:'',
        showRestore:true,
        showSave:true,
        pluginSettings:{
          settings:[],
        },
        pluginNameList:[],
      },
      inboundRespModal:{
        show:false,
        content:''
      },
      outboundReqModal:{
        show:false,
        index:0,
        fromIndex:-1,
        matchType:'0',
        content:''
      },
      outboundRespModal:{
        show:false,
        selectedTab:'ddl',
        ddl:'',
        index:0,
        fromIndex:-1,
        content:'',
        protocol:'',
        showRestore:true,
        showSave:true,
        pluginSettings:{
          settings:[],
        },
        pluginNameList:[],
      },
    }
  },
  created () {
    this.prepareMenu()
    this.getTestData()
  },
  methods: {
    prepareMenu(){
      this.headerMenu = [
        {name:'otdd',url:'/otdd'},
      ]
      this.leftBarMenu = [
        {name:'Edit',url:'/edit/'+this.testId},
      ]
    },
    getTestData(){
      document.title = 'edit test['+this.testId+']'
      this.$api.post('edit/getEditTest', {id:this.testId} , r => {
        this.testData = r.data
        this.moduleId = this.testData.moduleId
        this.$api.post('module/getModule', {id:this.moduleId}, r => {
          this.headerMenu.push({name:r.data.name,url:'/module/'+this.moduleId})
          this.headerMenu.push({name:'edit',url:'/edit/'+this.testId})
        })

        var size = r.data.outbounds.length
        for (var i = 0; i < r.data.outbounds.length; i++) {
          if ( r.data.responseTimestamp < r.data.outbounds[i].responseTimestamp ) {
            size = i
            break
          }
        }
        this.inboundRespTop = size * this.heightPerOutboundCall
        if(size>0){
          this.inboundRespTop = this.inboundRespTop + 16
        }
        this.splitLineHeight = (r.data.outbounds.length)*this.heightPerOutboundCall+160
        if(this.splitLineHeight<280){
          this.splitLineHeight = 280
        }

        this.$api.post('teststore/getTest', {moduleId:this.testData.moduleId,id:this.testData.fromId} , s => {
          this.originTest = s.data
        })
      })
    },
    inboundReqClicked(){
      this.parseInboundReqToDDL(true)
      this.$api.post('plugin/getPluginList', {} , r => {
        this.inboundReqModal.pluginNameList = r.data
      })
      this.inboundReqModal.originContent = this.$util.toPrettyHtml(this.base64decode(this.originTest.inbound.request))
      this.inboundReqModal.showRestore = true
      this.inboundReqModal.show = true
    },
    parseInboundReqToDDL(refreshPluginSetting){
      this.$api.post('ddl/parseInboundReqToDDL', {id:this.testId,testStoreType:'EDITED_TEST'},r => {
        this.inboundReqModal.ddl = r.data.ddl
        this.inboundReqModal.pluginSettings.pluginName = r.data.pluginName
        if(refreshPluginSetting){
          this.onInboundReqDDLPluginChanged(this.inboundReqModal.pluginSettings.pluginName)
        }
      })
    },
    onInboundReqDDLPluginChanged(value){
      if(value){
        var url = 'plugin/getPluginSettings'
        this.$api.post(url, {moduleId:this.testData.moduleId,pluginName:value} , r => {
          this.inboundReqModal.pluginSettings.settings = r.data.request
        })
      }
    },
    reInboundReqToDDL(){
      this.inboundReqModal.selectedTab = 'content'
      this.inboundReqTabClicked(this.inboundReqModal.selectedTab)
    },
    inboundRespClicked(){
      this.inboundRespModal.show = true
      this.inboundRespModal.content = this.$util.toPrettyHtml(this.base64decode(this.testData.inbound.response))
    },
    outboundReqClicked(index){
      var call = this.testData.outbounds[index]
      this.outboundReqModal.index = index
      this.outboundReqModal.fromIndex = call.fromIndex
      this.outboundReqModal.show = true
      this.outboundReqModal.matchType = '0'
      if(call.matchType==1){
        this.outboundReqModal.matchType = '1'
      }
      this.outboundReqModal.content = this.base64decode(call.request)
    },
    outboundResponseClicked(index){
      var call = this.testData.outbounds[index]
      this.outboundRespModal.pluginSettings = {settings:[]}
      this.outboundRespModal.index = index
      this.outboundRespModal.protocol = call.protocol
      this.outboundRespModal.showRestore = false
      this.outboundRespModal.fromIndex = call.fromIndex
      this.outboundRespModal.content = this.$util.toPrettyHtml(this.base64decode(call.response))
      this.outboundRespModal.originContent = ''
      if(call.fromIndex>=0&&this.originTest.outbounds.length>call.fromIndex){
        var originCall = this.originTest.outbounds[call.fromIndex]
        this.outboundRespModal.originContent = this.$util.toPrettyHtml(this.base64decode(originCall.response))
      }
      this.parseOutboundRespToDDL(index,true)
      this.$api.post('plugin/getPluginList', {} , r => {
        this.outboundRespModal.pluginNameList = r.data
      })
      this.outboundRespModal.show = true
    },
    reParseOutboundRespToDDL(){
      this.outboundRespModal.selectedTab = 'content'
      this.outboundRespTabClicked(this.outboundRespModal.selectedTab)
    },
    parseOutboundRespToDDL(index,refreshPluginSetting){
      this.$api.post('ddl/parseOutboundRespToDDL', {id:this.testId,index:index,pluginSettings:this.outboundRespModal.pluginSettings,testStoreType:'EDITED_TEST'},r => {
        if(r.data.ddl!=null&&r.data.ddl!=''){
          this.outboundRespModal.ddl = r.data.ddl
        }
        else{
          var call = this.testData.outbounds[index]
          if(call.response){
            this.outboundRespModal.ddl = 'failed to parse.'
          }
          else{
            this.outboundRespModal.ddl = ''
          }
        }
        this.outboundRespModal.protocol = r.data.protocol
        this.outboundRespModal.pluginSettings.pluginName = r.data.pluginName
        if(refreshPluginSetting){
          this.onOutboundRespDDLPluginChanged(this.outboundRespModal.pluginSettings.pluginName)
        }
        if(this.outboundRespModal.fromIndex>=0){
          this.outboundRespModal.showRestore = true
        }
      })
    },
    onOutboundRespDDLPluginChanged(value){
      if(value){
        var url = 'plugin/getPluginSettings'
        this.$api.post(url, {moduleId:this.testData.moduleId,pluginName:value} , r => {
          this.outboundRespModal.pluginSettings.settings = r.data.response
        })
      }
    },
    inboundReqTabClicked(name){
      if(name=='content'){
        this.inboundReqModal.showRestore = false
        this.$api.post('ddl/parseReqFromDDL', {ddl:this.inboundReqModal.ddl,pluginSettings:this.inboundReqModal.pluginSettings},r => {
          this.inboundReqModal.content = this.$util.toPrettyHtml(this.base64decode(r.data.bytes))
        },e=>{
          this.inboundReqModal.content = ''
          this.$Message.warning('failed to parse, please check the ddl.');
        })
      }
      else{
        this.inboundReqModal.showRestore = true
      }
    },
    inboundReqSaveClicked(){
      this.$api.post('edit/saveInboundReq', {id:this.testId,ddl:this.inboundReqModal.ddl,pluginSettings:this.inboundReqModal.pluginSettings},r =>{
        this.$Message.info('successfully saved.');
        this.inboundReqModal.show = false
        setInterval(() => {
          location.reload()
        }, 1000)
      })
    },
    inboundReqRestoreClicked(){
      this.$api.post('ddl/parseInboundReqToDDL', {id:this.testData.fromId,moduleId:this.moduleId,testStoreType:'ONLINE_RECORDED_TEST'},r => {
        this.inboundReqModal.ddl = r.data.ddl
      })
    },
    outboundReqSaveClicked(){
      var content = this.outboundReqModal.content
      var index = this.outboundReqModal.index
      var matchType = parseInt(this.outboundReqModal.matchType)
      this.$api.post('edit/saveOutboundReq', {id:this.testId,index:index,matchType:matchType,content:content} , r => {
        var call = this.testData.outbounds[this.outboundReqModal.index]
        call.request = this.base64encode(this.outboundReqModal.content)
        call.matchType = parseInt(this.outboundReqModal.matchType)
        this.outboundReqModal.show = false
        this.$Message.info('request successfully saved.');
      })
    },
    outboundReqRestoreClicked(){
      var fromIndex = this.outboundReqModal.fromIndex
      if(fromIndex>=0){
        var call = this.originTest.outbounds[fromIndex]
        this.outboundReqModal.content = this.base64decode(call.request)
        this.outboundReqModal.matchType = '0'
      }
    },
    outboundRespTabClicked(name){
      if(name=='content'){
        this.outboundRespModal.showRestore = false
        this.$api.post('ddl/parseRespFromDDL', {ddl:this.outboundRespModal.ddl,pluginSettings:this.outboundRespModal.pluginSettings},r => {
          this.outboundRespModal.content = this.$util.toPrettyHtml(this.base64decode(r.data.bytes))
        },e=>{
          this.outboundRespModal.content = ''
          this.$Message.warning('failed to parse, please check the ddl.');
        })
      }
      else{
        if(this.outboundRespModal.fromIndex>=0){
          this.outboundRespModal.showRestore = true
        }
      }
    },
    outboundRespSaveClicked(){
      this.$api.post('edit/saveOutboundResp', {id:this.testId,ddl:this.outboundRespModal.ddl,index:this.outboundRespModal.index,pluginSettings:this.outboundRespModal.pluginSettings},r =>{
        this.$Message.info('successfully saved.')
        this.outboundRespModal.show = false
        setInterval(() => {
          location.reload()
        }, 1000)
      })
    },
    outboundRespRestoreClicked(){
      var fromIndex = this.outboundRespModal.fromIndex
      if(fromIndex>=0){
        this.$api.post('ddl/parseOutboundRespToDDL', {id:this.testData.fromId,moduleId:this.moduleId,index:fromIndex,testStoreType:'ONLINE_RECORDED_TEST'},r => {
        if(r.data.ddl!=null&&r.data.ddl!=''){
            this.outboundRespModal.ddl = r.data.ddl
          }
          else{
            this.outboundRespModal.ddl = 'failed to parse.'
          }
          this.outboundRespModal.protocol = r.data.protocol
          this.outboundRespModal.pluginSettings.pluginName = r.data.pluginName
          this.onOutboundRespDDLPluginChanged(this.outboundRespModal.pluginSettings.pluginName)
        })
      }
    },
    onDeleteClicked(index){
      console.log('delete')
      var globleThis = this
      this.$Modal.confirm({
        title: 'confirm deletion',
        content: 'are you sure to delete this outbound call?',
        onOk:function(){
          this.$api.post('edit/deleteOutbound', {id:globleThis.testId,index:index},r => {
            location.reload()
          },e=>{
            this.$Message.warning('failed to delete.');
          })
        }
      })
    },
    onAddClicked(index){
      this.$api.post('edit/addOutbound', {id:this.testId,index:index},r => {
        this.$Message.info('new outbound call added. please click the request/response box to edit them.');
        setInterval(() => {
          location.reload()
        }, 1500)
      },e=>{
        this.$Message.warning('failed to add.');
      })
    },
    base64decode(str){
      return Base64.decode(str)
    },
    base64encode(str){
      return Base64.encode(str)
    },
    limitLength(str){
      if(str.length>116){
        str = str.substring(0,116) + '..'
      }
      return str
    },
  }
}
</script>

<style scoped>
.test-detail{
  width: 800px;
  overflow: auto;
  border: 1px solid #CCC;
  padding: 20px 20px 20px 20px;
}
.data-item{
  border:1px solid #bbb;
  border-radius:6px;
  float:left;
  margin:4px 1px;
  word-break: break-all;
  width:356px;
  height:44px;
  padding:2px 6px;
  text-align: left;
  cursor:pointer;
}
.data-item:hover{
  border-color:#2d8cf0;
}
.outbound{
  border:1px dashed #bbb;
  border-radius:6px;
  padding:4px 10px 4px 3px;
  margin:16px 2px;
  position:relative;
}
.outbound>.ivu-icon-minus-round{
  position: absolute;
  right: -12px;
  top: -9px;
}
.outbound>.ivu-icon,.icon-fix .ivu-icon{
  background: #2d8cf0;
  padding: 2px 6px;
}
.edit-outbound>.ivu-icon{
  background: #2d8cf0;
  padding: 2px 10px;
  float: left;
}
.edit-outbound>.ivu-icon:hover{
  cursor:pointer;
  background:#56a3f3;
}
.outbound>.ivu-icon:hover{
  cursor:pointer;
  background:#56a3f3;
}
.bytes .ivu-icon {
  float:left;
  top: 20px;
  position: relative;
}
.test-data .first{
  margin-top:68px;
}
.icon-fix{
  margin-top:43px;
}


.match-type{
  padding: 0px 0px 10px 0px;
  border-bottom: 1px dashed #2d8cf0;
  text-align:center;
}


</style>

<style>
.ivu-modal-confirm-footer button{
  padding: 2px 12px;
}
.ivu-modal-confirm-footer button span{
  font-size:12px;
}
</style>
